apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.block-feodo
spec:
  tier: security
  order: 100
  selector: all()
  types:
  - Egress
  egress:
  - action: Deny
    destination:
      selector: threatfeed == 'feodo'
