apiVersion: projectcalico.org/v3
kind: StagedGlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  order: 2000
  # target only these namespaces
  selector: "projectcalico.org/namespace in {'hipstershop','default'}"
  types:
  - Ingress
  - Egress
