apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  flowLogsFlushInterval: 10s
  flowLogsFileAggregationKindForAllowed: 1
  flowLogsEnableNetworkSets: true
  dnsLogsFlushInterval: 10s
  captureRotationSeconds: 300
  policySyncPathPrefix: /var/run/nodeagent
  flowLogsCollectTcpStats: true